background_opacity: 0.75
# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
# BEGIN ACE
colors:
  primary:
    background: '#101116'
    foreground: '#b7c6d7'
  cursor:
    text:       '#101116'
    cursor:     '#b7c6d7'
  normal:
    black:      '#101116'
    red:        '#637B92'
    green:      '#6E899E'
    yellow:     '#7694AC'
    blue:       '#7E9FC1'
    magenta:    '#819EBC'
    cyan:       '#85A9BE'
    white:      '#b7c6d7'
  bright:
    black:      '#808a96'
    red:        '#637B92'
    green:      '#6E899E'
    yellow:     '#7694AC'
    blue:       '#7E9FC1'
    magenta:    '#819EBC'
    cyan:       '#85A9BE'
    white:      '#b7c6d7'
# END ACE
    font:
      normal:
        family: MonoLisa
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }

